spring:
  application:
    name: fundamentos01
  
  # Configuración de la fuente de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: ups
    password: ups123
  
  # Configuración JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true  # Formatea SQL en los logs
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    ec.edu.ups.icc.fundamentos01: DEBUG

server:
  port: 8080